apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.dask.org/v1alpha1",
          "kind": "Dask",
          "metadata": {
            "name": "dask-sample"
          },
          "spec": {
            "jupyter": {
              "enabled": true,
              "image": {
                "repository": "daskdev/dask-notebook",
                "tag": "2021.12.0"
              },
              "name": "jupyter",
              "password": "sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c",
              "rbac": true,
              "replicas": 1,
              "serviceType": "ClusterIP"
            },
            "scheduler": {
              "enabled": true,
              "image": {
                "repository": "daskdev/dask",
                "tag": "2021.12.0"
              },
              "name": "scheduler",
              "replicas": 1,
              "servicePort": 8786,
              "serviceType": "ClusterIP"
            },
            "worker": {
              "image": {
                "dask_worker": "dask-worker",
                "repository": "daskdev/dask",
                "tag": "2021.12.0"
              },
              "name": "worker",
              "replicas": 2
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: dask-helm-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Dask
      name: dasks.charts.dask.org
      version: v1alpha1
  description: An operator to manage dask clusters.
  displayName: dask-helm-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - charts.dask.org
          resources:
          - dasks
          - dasks/status
          - dasks/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - Ingress
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: dask-helm-operator-controller-manager
      deployments:
      - name: dask-helm-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=dask-helm-operator
                image: dayeye2006/dask-helm-operator:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: dask-helm-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: dask-helm-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - big data
  - distributed computing
  links:
  - name: Dask Helm Operator
    url: https://dask-helm-operator.domain
  maintainers:
  - email: yuhui@convect.ai
    name: Yuhui Shi
  maturity: alpha
  provider:
    name: Yuhui Shi
    url: yuhui.me
  version: 0.0.1
