# permissions for end users to edit dasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dask-editor-role
rules:
- apiGroups:
  - charts.dask.org
  resources:
  - dasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.dask.org
  resources:
  - dasks/status
  verbs:
  - get
