apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dask-helm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: An operator to manage dask clusters.
  displayName: dask-helm-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - big data
  - distributed computing
  links:
  - name: Dask Helm Operator
    url: https://dask-helm-operator.domain
  maintainers:
  - email: yuhui@convect.ai
    name: Yuhui Shi
  maturity: alpha
  provider:
    name: Yuhui Shi
    url: yuhuishi.me
  version: 0.0.0
