apiVersion: charts.dask.org/v1alpha1
kind: Dask
metadata:
  name: dask-sample
spec:
  # Default values copied from <project_dir>/helm-charts/dask/values.yaml
  jupyter:
    enabled: true
    image:
      repository: daskdev/dask-notebook
      tag: 2021.12.0
    name: jupyter
    password: sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c
    rbac: true
    replicas: 1
    serviceType: ClusterIP
  scheduler:
    enabled: true
    image:
      repository: daskdev/dask
      tag: 2021.12.0
    name: scheduler
    replicas: 1
    servicePort: 8786
    serviceType: ClusterIP
  worker:
    image:
      dask_worker: dask-worker
      repository: daskdev/dask
      tag: 2021.12.0
    name: worker
    replicas: 2
  
