apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: {{ .Values.worker.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
      {{- if .Values.worker.annotations }}
      annotations:
        {{- toYaml .Values.worker.annotations | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.worker.image.pullSecrets | nindent 8 }}
      {{- if .Values.worker.mounts.volumes }}
      volumes:
        {{- toYaml .Values.worker.mounts.volumes | nindent 8}}
      {{- end }}
      containers:
        - name: {{ template "dask.fullname" . }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - {{ .Values.worker.image.dask_worker }}
          {{- if .Values.worker.custom_scheduler_url }}
            - {{ .Values.worker.custom_scheduler_url }}
          {{- else }}
            - {{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- end }}
          {{- if .Values.worker.resources.limits }}
            - --nthreads
            - {{ .Values.worker.threads_per_worker | default .Values.worker.resources.limits.cpu | default .Values.worker.default_resources.cpu | quote }}
            - --memory-limit
            - {{ .Values.worker.resources.limits.memory | default .Values.worker.default_resources.memory | quote }}
          {{- end }}
            - --no-dashboard
            - --dashboard-address
            - {{ .Values.worker.portDashboard | quote }}
          {{- if .Values.worker.port }}
            - --worker-port
            - {{ .Values.worker.port | quote }}
          {{- end }}
          {{- if .Values.worker.extraArgs }}
            {{ toYaml .Values.worker.extraArgs | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.worker.portDashboard }}
              name: dashboard
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.worker.env | nindent 12 }}

          {{- if .Values.worker.mounts.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.worker.mounts.volumeMounts | nindent 12 }}
          {{- end }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.worker.serviceAccountName }}
      serviceAccountName: {{ .Values.worker.serviceAccountName | quote }}
    {{- end }}
